# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-ChocolateyShortcut -ShortcutFilePath (Join-Path (Join-Path $Env:ChocolateyInstall 'bin') 'once.lnk') -TargetPath (Join-Path (Join-Path $toolsDir 'bin') 'once.bat')
